name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('go.mod') }}
        restore-keys: |
          go-mod-${{ runner.os }}-

    - name: Install Dependencies
      run: go mod download

    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@v0.5.2

    - name: Run Staticcheck
      run: staticcheck ./...
      env:
        STATICCHECK_CACHE: "/home/runner/work/_temp/staticcheck" # Explicit cache path

    - name: Build Project
      run: go build -v ./...

    - name: Run Tests with gotestsum
      run: |
        go install gotest.tools/gotestsum@latest
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
